### ISSUE TITLE
Quality Gate screenshot update

### ISSUE THREAD

**Issue by SychevIgor** [mpeder/azdevopssecurity#4]
Hello, could you update screenshot here? 
https://github.com/mpeder/azdevopssecurity/blob/master/practices-docs/06-practice.md
Current list is a bit shorter 
![image](https://user-images.githubusercontent.com/578954/61184135-bd999980-a652-11e9-8249-c44530368b62.png)

**Comment by mpeder** [comment]
@SychevIgor the list of things available here will always depend on the extensions installed in your organization. E.g. you could also installed ServiceNow integration here https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-servicenowchangerequestmanagement and that would show up.
